# Generated by Django 4.2.27 on 2025-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_darwin_id_product_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.CharField(default="Darwin", max_length=50),
        ),
    ]
