# Generated by Django 4.2.27 on 2025-12-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("shop", "external_id")},
        ),
    ]
