# Generated by Django 4.2.27 on 2025-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_shop_alter_product_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="external_id",
            field=models.CharField(max_length=50),
        ),
    ]
