# Generated by Django 4.2.27 on 2025-12-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
