# Generated by Django 4.2.27 on 2025-12-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_in_stock_product_last_seen_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="last_seen_at",
        ),
    ]
