# Generated by Django 4.2.27 on 2026-01-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_normalized_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="normalized_name",
        ),
    ]
