# Generated by Django 4.2.27 on 2026-01-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_product_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="variant",
            field=models.JSONField(default=dict),
        ),
    ]
