# Generated by Django 4.2.27 on 2026-01-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_name_alter_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="t_name",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="t_variant",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="variant",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
