# Generated by Django 4.2.27 on 2026-01-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0015_product_t_name_product_t_variant_alter_product_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop", models.CharField(max_length=100)),
                ("raw_category", models.CharField(max_length=255)),
                ("unified_category", models.CharField(max_length=100)),
            ],
        ),
    ]
