# Generated by Django 4.2.27 on 2026-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_categorymapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="t_category",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
