# Generated by Django 4.2.27 on 2026-01-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_product_canonical_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="normalized_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="normalized_variant",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
