# Generated by Django 4.2.27 on 2026-01-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_product_normalized_name_product_normalized_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="embedding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
