# Generated by Django 4.2.27 on 2026-01-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_userqueryembedding_precomputedsimilarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dirty",
            field=models.BooleanField(default=False),
        ),
    ]
