# Generated by Django 4.2.27 on 2026-01-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_productchangelog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductChangeLog",
        ),
    ]
