# Generated by Django 4.2.27 on 2026-01-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_delete_productchangelog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryMapping",
        ),
        migrations.RemoveField(
            model_name="product",
            name="normalized_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="normalized_variant",
        ),
    ]
