# Generated by Django 4.2.27 on 2026-01-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_delete_categorymapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutocompleteToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.CharField(db_index=True, max_length=255)),
                ("next_token", models.CharField(db_index=True, max_length=64)),
                ("count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["context"], name="products_au_context_28898b_idx"
                    ),
                    models.Index(
                        fields=["next_token"], name="products_au_next_to_0240cd_idx"
                    ),
                ],
                "unique_together": {("context", "next_token")},
            },
        ),
    ]
