# Generated by Django 4.2.27 on 2026-01-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0027_archivedproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="change_type",
            field=models.CharField(
                blank=True,
                choices=[("created", "created"), ("updated", "updated")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="changed_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
