# Generated by Django 4.2.27 on 2026-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_product_change_type_product_changed_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_categorized",
            field=models.BooleanField(default=False),
        ),
    ]
