# Generated by Django 4.2.27 on 2026-01-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0029_product_is_categorized"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_categorized",
        ),
    ]
