# Generated by Django 4.2.27 on 2026-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0030_remove_product_is_categorized"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedBrokenProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField(db_index=True)),
                ("external_id", models.CharField(max_length=50)),
                (
                    "canonical_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("variant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("in_stock", models.BooleanField(default=False)),
                ("shop", models.CharField(max_length=50)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ArchivedProduct",
        ),
        migrations.AddIndex(
            model_name="archivedbrokenproduct",
            index=models.Index(
                fields=["external_id"], name="products_ar_externa_8ee193_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="archivedbrokenproduct",
            index=models.Index(
                fields=["canonical_id"], name="products_ar_canonic_1dd6f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="archivedbrokenproduct",
            index=models.Index(fields=["shop"], name="products_ar_shop_b7f9e4_idx"),
        ),
    ]
