# Generated by Django 4.2.27 on 2026-01-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0034_productpricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpricehistory",
            name="archived_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_price_history",
                to="products.archivedproduct",
            ),
        ),
        migrations.AlterField(
            model_name="productpricehistory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_history",
                to="products.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="archivedbrokenproduct",
            unique_together={("shop", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="archivedproduct",
            unique_together={("shop", "external_id")},
        ),
        migrations.AlterUniqueTogether(
            name="productpricehistory",
            unique_together={("product", "archived_product", "recorded_at")},
        ),
        migrations.AddIndex(
            model_name="productpricehistory",
            index=models.Index(
                fields=["archived_product", "recorded_at"],
                name="products_pr_archive_8d5bba_idx",
            ),
        ),
    ]
