# Generated by Django 4.2.27 on 2026-01-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0036_productanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpricehistory",
            name="shop",
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="productpricehistory",
            index=models.Index(
                fields=["shop", "recorded_at"], name="products_pr_shop_234baa_idx"
            ),
        ),
    ]
