# Generated by Django 4.2.27 on 2026-01-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0037_productpricehistory_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedbrokenproduct",
            name="original_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="archivedproduct",
            name="original_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
