# Generated by Django 4.2.27 on 2026-01-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0038_alter_archivedbrokenproduct_original_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="change_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("restored", "restored"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
