# Generated by Django 4.2.27 on 2026-01-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0039_alter_product_change_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="change_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("restored", "restored"),
                    ("restored_from_broken", "restored_from_broken"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
