# Generated by Django 4.2.27 on 2026-01-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0040_alter_product_change_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
