# Generated by Django 4.2.27 on 2026-01-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0041_archivedbrokenproduct_url_archivedproduct_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="change_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="changed_fields",
        ),
    ]
