# Generated by Django 4.2.27 on 2026-01-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0042_remove_product_change_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
