# Generated by Django 4.2.27 on 2026-01-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0043_archivedbrokenproduct_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="embedding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="t_category",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="t_name",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="t_variant",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="embedding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="t_category",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="t_name",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="t_variant",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="archivedbrokenproduct",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="archivedproduct",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="productanalytics",
            name="price_change_count",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
