# Generated by Django 4.2.27 on 2026-01-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0045_remove_archivedbrokenproduct_products_ar_canonic_1dd6f8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedbrokenproduct",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="archivedbrokenproduct",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="archivedbrokenproduct",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="archivedproduct",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="archivedproduct",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="archivedproduct",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
