# Generated by Django 4.2.27 on 2026-01-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0046_alter_archivedbrokenproduct_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpricehistory",
            name="archived_broken_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_broken_price_history",
                to="products.archivedbrokenproduct",
            ),
        ),
    ]
