# Generated by Django 4.2.27 on 2026-01-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0047_productpricehistory_archived_broken_product"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productpricehistory",
            unique_together={
                ("product", "recorded_at"),
                ("archived_broken_product", "recorded_at"),
                ("archived_product", "recorded_at"),
            },
        ),
        migrations.AddIndex(
            model_name="productpricehistory",
            index=models.Index(
                fields=["archived_broken_product", "recorded_at"],
                name="products_pr_archive_4ae5bc_idx",
            ),
        ),
    ]
