# Generated by Django 4.2.27 on 2026-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0048_alter_productpricehistory_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="dirty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="dirty",
            field=models.BooleanField(default=False),
        ),
    ]
