# Generated by Django 4.2.27 on 2026-01-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0049_archivedbrokenproduct_dirty_archivedproduct_dirty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
