# Generated by Django 4.2.27 on 2026-02-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0050_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
