# Generated by Django 4.2.27 on 2026-02-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0051_archivedbrokenproduct_tags_archivedproduct_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivedbrokenproduct",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="archivedproduct",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
    ]
