# Generated by Django 4.2.27 on 2026-02-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0053_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
