categories = [
    {"ro": "accesorii apple", "en": "Apple accessories", "ru": "аксессуары Apple"},
    {
        "ro": "accesorii gaming",
        "en": "Gaming accessories",
        "ru": "геймерские аксессуары",
    },
    {
        "ro": "accesorii tableta",
        "en": "Tablet accessories",
        "ru": "аксессуары для планшетов",
    },
    {"ro": "accesorii tv", "en": "TV accessories", "ru": "аксессуары для телевизоров"},
    {"ro": "aspirator robot", "en": "Robot vacuum cleaners", "ru": "роботы-пылесосы"},
    {
        "ro": "birou calculator, mobilier",
        "en": "Computer desks and furniture",
        "ru": "компьютерные столы и мебель",
    },
    {
        "ro": "camera de supraveghere, securitate",
        "en": "Surveillance cameras and security",
        "ru": "камеры видеонаблюдения и безопасность",
    },
    {
        "ro": "birou, mobilier",
        "en": "Office desks and furniture",
        "ru": "офисные столы и мебель",
    },
    {
        "ro": "cabluri, accesorii",
        "en": "Cables and accessories",
        "ru": "кабели и аксессуары",
    },
    {"ro": "camera actiune", "en": "Action cameras", "ru": "экшн-камеры"},
    {
        "ro": "camera foto, fotografie",
        "en": "Digital cameras and photography",
        "ru": "цифровые фотоаппараты и фотография",
    },
    {
        "ro": "camera web, periferice pc",
        "en": "Webcams and PC peripherals",
        "ru": "веб-камеры и периферия для ПК",
    },
    {
        "ro": "cană, accesorii birou",
        "en": "Mugs and desk accessories",
        "ru": "кружки и офисные аксессуары",
    },
    {
        "ro": "carcasa pc, componente pc",
        "en": "PC cases and components",
        "ru": "корпуса и компоненты ПК",
    },
    {
        "ro": "casti gaming, audio",
        "en": "Gaming headsets and audio",
        "ru": "геймерские наушники и аудио",
    },
    {"ro": "casti, audio", "en": "Headphones and audio", "ru": "наушники и аудио"},
    {"ro": "console jocuri", "en": "Game consoles", "ru": "игровые консоли"},
    {
        "ro": "consumabile imprimanta",
        "en": "Printer consumables",
        "ru": "расходные материалы для принтеров",
    },
    {
        "ro": "controller jocuri, accesorii gaming",
        "en": "Game controllers and gaming accessories",
        "ru": "геймпады и игровые аксессуары",
    },
    {
        "ro": "docking station, accesorii pc",
        "en": "Docking stations and PC accessories",
        "ru": "док-станции и аксессуары для ПК",
    },
    {"ro": "ecrane proiectie", "en": "Projection screens", "ru": "проекционные экраны"},
    {
        "ro": "imprimanta, birou",
        "en": "Printers and office equipment",
        "ru": "принтеры и офисное оборудование",
    },
    {
        "ro": "incarcatoare, accesorii mobile",
        "en": "Chargers and mobile accessories",
        "ru": "зарядные устройства и мобильные аксессуары",
    },
    {"ro": "jocuri video", "en": "Video games", "ru": "видеоигры"},
    {
        "ro": "lampa birou, iluminat",
        "en": "Desk lamps and lighting",
        "ru": "настольные лампы и освещение",
    },
    {
        "ro": "laptop accessories",
        "en": "Laptop accessories",
        "ru": "аксессуары для ноутбуков",
    },
    {
        "ro": "laptop gaming, notebook gaming",
        "en": "Gaming laptops",
        "ru": "игровые ноутбуки",
    },
    {
        "ro": "boxe portabile, audio",
        "en": "Portable speakers and audio",
        "ru": "портативные колонки и аудио",
    },
    {
        "ro": "boxe, audio",
        "en": "speakers and audio",
        "ru": "колонки и аудио",
    },
    {
        "ro": "boxe pc, audio",
        "en": "PC speakers and audio",
        "ru": "колонки для ПК и аудио",
    },
    {
        "ro": "echipamente de înregistrare audio, studio",
        "en": "Audio recording equipment and studio gear",
        "ru": "оборудование для аудиозаписи и студии",
    },
    {
        "ro": "laptop, notebook",
        "en": "Laptops and notebooks",
        "ru": "ноутбуки и портативные компьютеры",
    },
    {"ro": "media player", "en": "Media players", "ru": "медиаплееры"},
    {
        "ro": "memorie ram, componente pc",
        "en": "RAM and PC components",
        "ru": "оперативная память и компоненты ПК",
    },
    {
        "ro": "merchandising, fan gear",
        "en": "Merchandising and fan gear",
        "ru": "мерчандайзинг и фанатская атрибутика",
    },
    {
        "ro": "merchandising, gaming",
        "en": "Gaming merchandising",
        "ru": "геймерский мерчандайзинг",
    },
    {
        "ro": "microfon gaming, audio",
        "en": "Gaming microphones and audio",
        "ru": "геймерские микрофоны и аудио",
    },
    {"ro": "microfon, audio", "en": "Microphones and audio", "ru": "микрофоны и аудио"},
    {"ro": "mini pc, apple", "en": "Apple Mac mini", "ru": "мини-ПК Apple"},
    {
        "ro": "pc, desktop",
        "en": "PCs",
        "ru": "ПК и настольные компьютеры",
    },
    {
        "ro": "mini pc, desktop",
        "en": "Mini PCs",
        "ru": "мини-ПК и настольные компьютеры",
    },
    {
        "ro": "monitor gaming, display",
        "en": "Gaming monitors",
        "ru": "игровые мониторы",
    },
    {
        "ro": "monitor, display",
        "en": "Monitors and displays",
        "ru": "мониторы и дисплеи",
    },
    {
        "ro": "mouse gaming, periferice pc",
        "en": "Gaming mice and PC peripherals",
        "ru": "геймерские мыши и периферия для ПК",
    },
    {
        "ro": "mouse pad gaming, accesorii pc",
        "en": "Gaming mouse pads and PC accessories",
        "ru": "геймерские коврики и аксессуары для ПК",
    },
    {
        "ro": "mouse pad, accesorii pc",
        "en": "Mouse pads and PC accessories",
        "ru": "коврики для мыши и аксессуары для ПК",
    },
    {
        "ro": "mouse, periferice pc",
        "en": "Mice and PC peripherals",
        "ru": "компьютерные мыши и периферия для ПК",
    },
    {"ro": "pc all in one, apple", "en": "Apple iMac", "ru": "моноблоки Apple"},
    {
        "ro": "pc all in one, desktop",
        "en": "All-in-One PCs",
        "ru": "моноблоки и настольные компьютеры",
    },
    {
        "ro": "pc desktop, apple",
        "en": "Apple Mac Studio",
        "ru": "настольные компьютеры Apple",
    },
    {
        "ro": "pc desktop, sistem complet",
        "en": "Desktop PCs, complete systems",
        "ru": "настольные ПК, готовые системы",
    },
    {
        "ro": "pc gaming, desktop gaming",
        "en": "Gaming desktop PCs",
        "ru": "игровые ПК и гейминг-компьютеры",
    },
    {
        "ro": "periferice pc",
        "en": "PC peripherals",
        "ru": "периферийные устройства для ПК",
    },
    {
        "ro": "placa de baza, motherboard, componente pc",
        "en": "Motherboards and PC components",
        "ru": "материнские платы и компоненты ПК",
    },
    {
        "ro": "placa video, gpu, componente pc",
        "en": "Graphics cards and PC components",
        "ru": "видеокарты и компоненты ПК",
    },
    {
        "ro": "power bank, accesorii mobile",
        "en": "Power banks and mobile accessories",
        "ru": "пауэрбанки и мобильные аксессуары",
    },
    {
        "ro": "procesor, cpu, componente pc",
        "en": "Processors and PC components",
        "ru": "процессоры и компоненты ПК",
    },
    {
        "ro": "proiectoare, display",
        "en": "Projectors and displays",
        "ru": "проекционные устройства и дисплеи",
    },
    {
        "ro": "protectie retea, birou",
        "en": "Network protection and office",
        "ru": "защита сети и офис",
    },
    {
        "ro": "protectie telefon, accesorii mobile",
        "en": "Phone protection and mobile accessories",
        "ru": "защита телефона и мобильные аксессуары",
    },
    {
        "ro": "racire pc, accesorii",
        "en": "PC cooling and accessories",
        "ru": "охлаждение ПК и аксессуары",
    },
    {
        "ro": "racire pc, cooler, componente pc",
        "en": "PC cooling, coolers and components",
        "ru": "охлаждение ПК, кулеры и компоненты",
    },
    {
        "ro": "router, dispozitiv retea",
        "en": "Routers and network devices",
        "ru": "роутеры и сетевые устройства",
    },
    {
        "ro": "router, wifi, dispozitiv retea",
        "en": "WiFi routers and network devices",
        "ru": "WiFi роутеры и сетевые устройства",
    },
    {"ro": "scanner, birou", "en": "Scanners and office", "ru": "сканеры и офис"},
    {"ro": "scaun birou, mobilier", "en": "Office chairs", "ru": "офисные кресла"},
    {
        "ro": "scaun gaming, mobilier birou",
        "en": "Gaming chairs",
        "ru": "геймерские кресла",
    },
    {"ro": "shredder, birou", "en": "Office shredders", "ru": "офисные шредеры"},
    {"ro": "smartphone, telefon mobil", "en": "Smartphones", "ru": "смартфоны"},
    {"ro": "smartwatch", "en": "Smartwatches", "ru": "умные часы"},
    {"ro": "software", "en": "Software", "ru": "ПО"},
    {
        "ro": "sticlă apă, accesorii birou",
        "en": "Water bottles and desk accessories",
        "ru": "бутылки для воды и офисные аксессуары",
    },
    {
        "ro": "stocare externa, hdd, accesorii pc",
        "en": "External storage and PC accessories",
        "ru": "внешнее хранилище и аксессуары ПК",
    },
    {
        "ro": "ochelari vr, gadgeturi gaming",
        "en": "VR glasses and gaming gadgets",
        "ru": "VR очки и игровые гаджеты",
    },
    {
        "ro": "stocare interna, hdd, componente pc",
        "en": "Internal HDD storage",
        "ru": "внутренние HDD и компоненты ПК",
    },
    {
        "ro": "stocare interna, ssd, componente pc",
        "en": "Internal SSD storage",
        "ru": "внутренние SSD и компоненты ПК",
    },
    {
        "ro": "stocare interna, ssd, hdd, componente pc",
        "en": "Internal SSD/HDD storage",
        "ru": "внутренние SSD/HDD и компоненты ПК",
    },
    {
        "ro": "suport auto telefon, accesorii auto",
        "en": "Car phone holders and accessories",
        "ru": "автомобильные держатели и аксессуары",
    },
    {
        "ro": "suport monitor, accesorii birou",
        "en": "Monitor stands and desk accessories",
        "ru": "подставки для мониторов и офисные аксессуары",
    },
    {
        "ro": "suport tv, accesorii tv",
        "en": "TV stands and accessories",
        "ru": "подставки для ТВ и аксессуары",
    },
    {
        "ro": "sursa pc, psu, componente pc",
        "en": "PC power supplies and components",
        "ru": "блоки питания ПК и компоненты",
    },
    {
        "ro": "switch, poe, dispozitiv retea",
        "en": "Switches, PoE, network devices",
        "ru": "коммутаторы, PoE и сетевые устройства",
    },
    {"ro": "tableta", "en": "Tablets", "ru": "планшеты"},
    {"ro": "tableta grafica", "en": "Graphics tablets", "ru": "графические планшеты"},
    {
        "ro": "tableta grafica, periferice pc",
        "en": "Graphics tablets and PC peripherals",
        "ru": "графические планшеты и периферия ПК",
    },
    {
        "ro": "tastatura gaming, periferice pc",
        "en": "Gaming keyboards and PC peripherals",
        "ru": "геймерские клавиатуры и периферия ПК",
    },
    {
        "ro": "tastatura, periferice pc",
        "en": "Keyboards and PC peripherals",
        "ru": "клавиатуры и периферия ПК",
    },
    {
        "ro": "telefon fix, dect, birou",
        "en": "Landline phones and office",
        "ru": "стационарные телефоны и офис",
    },
    {
        "ro": "telefon mobil, buton, feature phone",
        "en": "Feature phones",
        "ru": "кнопочные телефоны",
    },
    {"ro": "televizor", "en": "Televisions", "ru": "телевизоры"},
    {
        "ro": "drona, echipament aerian",
        "en": "Drones and aerial equipment",
        "ru": "дроны и аэрооборудование",
    },
    {
        "ro": "accesorii smart home, automatizare",
        "en": "Smart home accessories and automation",
        "ru": "умные аксессуары для дома и автоматизация",
    },
    {
        "ro": "radiouri portabile, echipamente comunicare",
        "en": "Portable radios and communication equipment",
        "ru": "портативные рации и оборудование связи",
    },
    {
        "ro": "trepied, accesorii foto video",
        "en": "Tripods and photo/video accessories",
        "ru": "штативы и фото/видео аксессуары",
    },
    {
        "ro": "stabilizator, accesorii video",
        "en": "Stabilizers and video accessories",
        "ru": "стабилизаторы и видео аксессуары",
    },
    {
        "ro": "curele smartwatch, brățări wearable",
        "en": "Smartwatch straps and wearable bands",
        "ru": "ремни для умных часов и носимые браслеты",
    },
]

synonym_rules = {
    # Resolution conversions
    "3840 x 2160": ["4K", "UHD", "Ultra HD"],
    "1920 x 1080": ["Full HD", "FHD", "1080p"],
    "2560 x 1440": ["QHD", "2K", "1440p"],
    "7680 x 4320": ["8K", "Ultra HD 8K"],
    "1280 x 720": ["HD", "720p"],
    # Common technology abbreviations
    "HDMI": ["High Definition Multimedia Interface"],
    "USB-C": ["USB Type-C", "Type-C"],
    "USB 3.0": ["USB 3", "SuperSpeed USB"],
    "USB 3.1": ["USB 3.1 Gen 2", "SuperSpeed+"],
    "USB 3.2": ["USB 3.2 Gen 2x2"],
    "WiFi 6": ["802.11ax", "Wi-Fi 6"],
    "WiFi 5": ["802.11ac", "Wi-Fi 5"],
    "Bluetooth 5.0": ["BT 5.0", "Bluetooth 5"],
    "Bluetooth 5.1": ["BT 5.1"],
    "Bluetooth 5.2": ["BT 5.2"],
    "Bluetooth 5.3": ["BT 5.3"],
    # Storage capacity formats
    "1 TB": ["1000 GB", "1024 GB", "Terabyte"],
    "500 GB": ["0.5 TB", "512 GB"],
    "256 GB": ["0.25 TB"],
    "128 GB": [],
    "64 GB": [],
    # RAM formats
    "16 GB": ["16000 MB", "16G"],
    "8 GB": ["8000 MB", "8G"],
    "32 GB": ["32000 MB", "32G"],
    "64 GB": ["64000 MB", "64G"],
    # Processor terms
    "Intel Core i7": ["i7", "Intel i7"],
    "Intel Core i5": ["i5", "Intel i5"],
    "Intel Core i3": ["i3", "Intel i3"],
    "AMD Ryzen 7": ["Ryzen 7", "R7"],
    "AMD Ryzen 5": ["Ryzen 5", "R5"],
    "AMD Ryzen 3": ["Ryzen 3", "R3"],
    # Graphics cards
    "NVIDIA GeForce RTX": ["RTX", "NVIDIA RTX"],
    "NVIDIA GeForce GTX": ["GTX", "NVIDIA GTX"],
    "AMD Radeon RX": ["RX", "AMD RX"],
    # Display features
    "IPS": ["In-Plane Switching"],
    "OLED": ["Organic LED"],
    "LED": ["Light Emitting Diode"],
    "LCD": ["Liquid Crystal Display"],
    "AMOLED": ["Active Matrix OLED"],
    "Retina": ["Apple Retina Display"],
    # Audio terms
    "Dolby Atmos": ["Dolby Atmos Sound"],
    "DTS:X": ["DTS X", "DTS Surround"],
    "Hi-Res Audio": ["High Resolution Audio"],
    "Noise Cancelling": ["Active Noise Cancellation", "ANC"],
    # Gaming terms
    "144Hz": ["144 Hz", "144 Hertz"],
    "240Hz": ["240 Hz", "240 Hertz"],
    "360Hz": ["360 Hz", "360 Hertz"],
    "G-Sync": ["NVIDIA G-Sync"],
    "FreeSync": ["AMD FreeSync"],
    "RGB": ["RGB Lighting", "RGB LED"],
    # Phone features
    "5G": ["Fifth Generation", "5G Network"],
    "4G": ["Fourth Generation", "LTE"],
    "Dual SIM": ["Dual SIM Card", "Two SIM"],
    "NFC": ["Near Field Communication"],
    "Face ID": ["Face Recognition", "Facial Recognition"],
    "Touch ID": ["Fingerprint Scanner", "Fingerprint ID"],
    # Battery terms
    "mAh": ["milliampere-hour"],
    "Fast Charging": ["Quick Charge", "Rapid Charging"],
    "Wireless Charging": ["Qi Charging", "Inductive Charging"],
    # Camera terms
    "MP": ["Megapixel", "Mega Pixel"],
    "4K Video": ["Ultra HD Video", "2160p Video"],
    "Optical Zoom": ["Optical Zoom Lens"],
    "Digital Zoom": [],
    "Image Stabilization": ["IS", "Stabilization"],
    # Network terms
    "Gigabit Ethernet": ["GbE", "1000 Mbps Ethernet"],
    "PoE": ["Power over Ethernet"],
    "Mesh": ["Mesh Network", "Mesh System"],
    # Common product variations
    "Wireless": ["Wi-Fi", "Cordless"],
    "Bluetooth": ["BT", "Wireless Bluetooth"],
    "Wired": ["Cable", "With Cable"],
    "Portable": ["Mobile", "Travel"],
    "Rechargeable": ["Battery Operated", "Built-in Battery"],
    # Size formats
    "Inch": ['"', "Inches"],
    "cm": ["centimeter", "centimeters"],
}
