# Generated by Django 4.2.27 on 2025-12-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="darwin_id",
            new_name="external_id",
        ),
    ]
