# Generated by Django 4.2.27 on 2026-01-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_in_stock_remove_product_last_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="normalized_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
