# Generated by Django 4.2.27 on 2026-01-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_product_normalized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="normalized_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
