# Generated by Django 4.2.27 on 2026-01-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_product_normalized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
