# Generated by Django 4.2.27 on 2026-01-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_product_name_alter_product_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="variant",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
