# Generated by Django 4.2.27 on 2026-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_product_t_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="canonical_id",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
