# Generated by Django 4.2.27 on 2026-01-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_product_dirty"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop", models.CharField(max_length=50)),
                ("product_id", models.IntegerField()),
                ("change_type", models.CharField(max_length=10)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["shop", "timestamp"], name="products_pr_shop_951049_idx"
                    ),
                    models.Index(
                        fields=["shop", "product_id"],
                        name="products_pr_shop_60bc22_idx",
                    ),
                ],
            },
        ),
    ]
