# Generated by Django 4.2.27 on 2026-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0031_archivedbrokenproduct_delete_archivedproduct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField(db_index=True)),
                ("external_id", models.CharField(max_length=50)),
                (
                    "canonical_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("variant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("in_stock", models.BooleanField(default=False)),
                ("shop", models.CharField(max_length=50)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["external_id"], name="products_ar_externa_27e26c_idx"
                    ),
                    models.Index(
                        fields=["canonical_id"], name="products_ar_canonic_872ca6_idx"
                    ),
                    models.Index(fields=["shop"], name="products_ar_shop_ad6181_idx"),
                ],
            },
        ),
    ]
