# Generated by Django 4.2.27 on 2026-01-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0032_archivedproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop", models.CharField(max_length=50)),
                ("external_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
