# Generated by Django 4.2.27 on 2026-01-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0044_archivedbrokenproduct_brand_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="archivedbrokenproduct",
            name="products_ar_canonic_1dd6f8_idx",
        ),
        migrations.RemoveIndex(
            model_name="archivedproduct",
            name="products_ar_canonic_872ca6_idx",
        ),
        migrations.RemoveField(
            model_name="archivedbrokenproduct",
            name="canonical_id",
        ),
        migrations.RemoveField(
            model_name="archivedproduct",
            name="canonical_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="canonical_id",
        ),
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="identical_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="archivedbrokenproduct",
            name="similar_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="identical_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="archivedproduct",
            name="similar_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="identical_id",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="similar_id",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name="archivedbrokenproduct",
            index=models.Index(
                fields=["similar_id"], name="products_ar_similar_0ed89c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="archivedproduct",
            index=models.Index(
                fields=["similar_id"], name="products_ar_similar_a6caf1_idx"
            ),
        ),
    ]
