# MERGE AGGREGATED
FUZZY_THRESHOLD_CLUSTER = 85
COSINE_THRESHOLD_CLUSTER = 0.85

# AUTOCOMPLETE
AUTOCOMPLETE_LIMIT = 15

# QUERY
CACHE_TTL_LAYER1 = 60 * 15
LAYER1_LIMIT = 20
LAYER2_LIMIT = 50
LAYER3_LIMIT = 50

# RANK FILTER
CUT_OFF = 0.5
BASE_FRACTION = 0.4
STEEPNESS = 10
